SCHEDULE_OBJS = output/myOS/kernel/schedule/QueueFIFO.o \
             output/myOS/kernel/schedule/QueuePRI.o \
			  output/myOS/kernel/schedule/QueueSJF.o \
			 output/myOS/kernel/schedule/scheduler.o \
			 output/myOS/kernel/schedule/task.o 