include $(SRC_RT)/myOS/kernel/timer/Makefile
include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/schedule/Makefile

KERNEL_OBJS = ${TIMER_OBJS} \
              ${MEM_OBJS} \
              ${SCHEDULE_OBJS}